version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      discovery.type: single-node
  kibana:
    build: ./kibana
    ports:
      - 5601:5601
  logstash:
    build: ./logstash
    volumes: 
      - ./logstash/pipeline:/usr/share/logstash/pipeline
  filebeat:
    build: ./filebeat
    volumes:
      - ./filebeat/prospectors:/usr/share/filebeat/prospectors.d
      - ./filebeat/logs:/logs